<a href="https://colab.research.google.com/github/KARRIRAJKUMAR/AI_ML_Avanthi_RAJ-KUMAR/blob/main/day4Q.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Create a 10x10 array with random values and find the minimum and maximum values

In [5]:
import numpy as np

In [7]:
a = np.random.randint(1,100, size = (10,10))
print("Max = ", np.max(a))
print("Min = ", np.min(a))

Max =  99
Min =  1


Create a 2d array with 1 on the border and 0 inside

In [11]:
x=np.ones((4,4))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


13.Create a 8x8 matrix and fill it with a checkerboard pattern

In [12]:
x=np.zeros((8,8))
x[1::2,::2]=1
x[::2,1::2]=1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

14.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [21]:
x=np.random.rand(5,3)
print(x)
y=np.random.rand(3,2)
print(y)
np.matmul(x,y)

[[0.18256877 0.01935735 0.1966195 ]
 [0.06649716 0.39815596 0.03930886]
 [0.57506816 0.82972719 0.93772249]
 [0.50785052 0.93581872 0.85215221]
 [0.15446895 0.24325415 0.71922112]]
[[0.95473907 0.73591605]
 [0.92800459 0.10599223]
 [0.13342379 0.79502892]]


array([[0.21850296, 0.2927252 ],
       [0.43822273, 0.12238944],
       [1.44414516, 1.25666302],
       [1.46700617, 1.15041051],
       [0.46917972, 0.71126082]])

15.How to find common values between two arrays?

In [24]:
x = np.array([0, 1, 2, 3, 4])
y=np.array([1, 3, 4])
print(np.intersect1d(x,y))

[1 3 4]


17.Create a random vector of size 10 and sort it

In [28]:
x=np.random.rand(10)
print(x)
x.sort()
print(x)

[0.33436666 0.34482779 0.91926314 0.99286851 0.37463634 0.66788989
 0.97524859 0.93172226 0.88605143 0.42120632]
[0.33436666 0.34482779 0.37463634 0.42120632 0.66788989 0.88605143
 0.91926314 0.93172226 0.97524859 0.99286851]
