<a href="https://colab.research.google.com/github/KARRIRAJKUMAR/AI_ML_Avanthi_RAJ-KUMAR/blob/main/DAY_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install numpy

In [4]:
import numpy as np

In [6]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [10]:
a.dtype

dtype('int64')

In [11]:
a.size

3

In [15]:
a=np.array([1,2,3],dtype='int64')
a.itemsize

8

In [16]:
a.nbytes

24

In [32]:
x=np.ones((5,5))
#print(x)
y=np.zeros((3,3))
y[1,1]=9
x[1:4,-4:-1]=y
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
